[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "qemu-system-arm -M netduino2 -serial stdio -monitor none -nographic -kernel"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
